  name: Build to Production

  on:
    pull_request:
      branches:
        - develop

  jobs:
    deploy:
      name: Build
      runs-on: [ubuntu-latest]

      strategy:
        matrix:
          node-version: [14.x]

      steps:
        - uses: actions/checkout@v2

        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}

        - name: Yarn install
          run: yarn install

        - name: Build
          run: yarn build
