name: deploy-storybook

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: deploy-storybook
    runs-on: [ubuntu-latest]

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: deploy-storybook
        run: yarn deploy-storybook